image: node:9.11

pipelines:
  branches:
    master:
      - step:
          script:
            - yarn global add surge
            - yarn
            - yarn test
            - yarn lint
            - yarn build
            - surge build simple-mobx-blog.surge.sh
            - yarn build-storybook
            - surge storybook-static simple-mobx-blog-storybook.surge.sh
